// ============================================================
// OFFCLASS Demo Data
// All data is clearly labeled as DEMO DATA
// None of this represents real companies, deadlines, or guarantees
// ============================================================

import type { Skill, Opportunity, Tool, CareerPath, CampusEvent } from './types';

// ============================================================
// SKILLS
// ============================================================

export const demoSkills: Skill[] = [
  {
    id: 'skill-ui-ux',
    title: 'UI/UX Design',
    summary: 'Learn to design beautiful, functional digital interfaces that solve real problems.',
    category: 'Design',
    tags: ['design', 'figma', 'user-research', 'prototyping'],
    iconName: 'Palette',
    difficulty: 'beginner',
    learningTimeWeeks: 8,
    monetizationPotential: ['Freelance design projects', 'Internships at startups', 'Design contests'],
    careerApplications: ['UI Designer', 'UX Researcher', 'Product Designer'],
    beginnerProject: 'Redesign a mobile app screen',
    portfolioProject: 'Design a complete app from research to prototype',
    prerequisites: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
  {
    id: 'skill-web-dev',
    title: 'Web Development',
    summary: 'Build websites and web applications from scratch using modern technologies.',
    category: 'Tech',
    tags: ['html', 'css', 'javascript', 'react', 'coding'],
    iconName: 'Code2',
    difficulty: 'beginner',
    learningTimeWeeks: 12,
    monetizationPotential: ['Freelance web projects', 'Client websites', 'SaaS products'],
    careerApplications: ['Frontend Developer', 'Full-stack Developer', 'Freelance Developer'],
    beginnerProject: 'Build a personal portfolio website',
    portfolioProject: 'Build a full-stack web application',
    prerequisites: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
  {
    id: 'skill-video-editing',
    title: 'Video Editing',
    summary: 'Create professional video content for social media, brands, and personal projects.',
    category: 'Creative',
    tags: ['video', 'premiere', 'content-creation', 'youtube'],
    iconName: 'Video',
    difficulty: 'beginner',
    learningTimeWeeks: 6,
    monetizationPotential: ['YouTube editing', 'Social media management', 'Brand content'],
    careerApplications: ['Video Editor', 'Content Creator', 'Social Media Manager'],
    beginnerProject: 'Edit a 60-second reel',
    portfolioProject: 'Create a branded video series',
    prerequisites: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
  {
    id: 'skill-copywriting',
    title: 'Copywriting',
    summary: 'Write persuasive content that sells products, builds brands, and drives engagement.',
    category: 'Writing',
    tags: ['writing', 'marketing', 'content', 'ads'],
    iconName: 'PenTool',
    difficulty: 'beginner',
    learningTimeWeeks: 4,
    monetizationPotential: ['Freelance copy', 'Social media writing', 'Email marketing'],
    careerApplications: ['Copywriter', 'Content Strategist', 'Marketing Specialist'],
    beginnerProject: 'Write 5 ad copy variations for a product',
    portfolioProject: 'Create a complete brand messaging guide',
    prerequisites: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
  {
    id: 'skill-data-analysis',
    title: 'Data Analysis',
    summary: 'Turn raw data into insights using Python, Excel, and visualization tools.',
    category: 'Tech',
    tags: ['data', 'python', 'excel', 'analytics', 'visualization'],
    iconName: 'BarChart3',
    difficulty: 'intermediate',
    learningTimeWeeks: 10,
    monetizationPotential: ['Data consulting', 'Research assistance', 'Business analytics'],
    careerApplications: ['Data Analyst', 'Business Analyst', 'Research Analyst'],
    beginnerProject: 'Analyze a public dataset and create a report',
    portfolioProject: 'Build an interactive dashboard',
    prerequisites: ['Basic spreadsheet skills'],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
  {
    id: 'skill-digital-marketing',
    title: 'Digital Marketing',
    summary: 'Learn to grow brands online through social media, SEO, ads, and content strategy.',
    category: 'Business',
    tags: ['marketing', 'social-media', 'seo', 'ads', 'growth'],
    iconName: 'Megaphone',
    difficulty: 'beginner',
    learningTimeWeeks: 8,
    monetizationPotential: ['Social media management', 'SEO consulting', 'Ad management'],
    careerApplications: ['Digital Marketer', 'Growth Hacker', 'Social Media Manager'],
    beginnerProject: 'Create a 30-day content calendar',
    portfolioProject: 'Run a mock campaign with analytics',
    prerequisites: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
  {
    id: 'skill-ai-ml',
    title: 'AI & Machine Learning',
    summary: 'Understand and build AI-powered applications using modern tools and frameworks.',
    category: 'Tech',
    tags: ['ai', 'machine-learning', 'python', 'deep-learning'],
    iconName: 'Brain',
    difficulty: 'advanced',
    learningTimeWeeks: 16,
    monetizationPotential: ['AI consulting', 'Building AI tools', 'Research projects'],
    careerApplications: ['ML Engineer', 'AI Researcher', 'Data Scientist'],
    beginnerProject: 'Build a simple prediction model',
    portfolioProject: 'Deploy an AI-powered application',
    prerequisites: ['Python basics', 'Basic mathematics'],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
  {
    id: 'skill-photography',
    title: 'Photography',
    summary: 'Capture stunning photos for brands, events, products, and personal portfolios.',
    category: 'Creative',
    tags: ['photography', 'editing', 'lightroom', 'visual'],
    iconName: 'Camera',
    difficulty: 'beginner',
    learningTimeWeeks: 6,
    monetizationPotential: ['Event photography', 'Product photography', 'Stock photos'],
    careerApplications: ['Photographer', 'Visual Content Creator', 'Brand Photographer'],
    beginnerProject: 'Create a themed photo series of 10 images',
    portfolioProject: 'Shoot a complete brand lookbook',
    prerequisites: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
  {
    id: 'skill-mobile-dev',
    title: 'Mobile App Development',
    summary: 'Build native and cross-platform mobile apps using React Native or Flutter.',
    category: 'Tech',
    tags: ['mobile', 'react-native', 'flutter', 'apps'],
    iconName: 'Code2',
    difficulty: 'intermediate',
    learningTimeWeeks: 14,
    monetizationPotential: ['Freelance app development', 'Startup MVPs', 'App store publishing'],
    careerApplications: ['Mobile Developer', 'Cross-Platform Developer', 'App Engineer'],
    beginnerProject: 'Build a simple to-do app with local storage',
    portfolioProject: 'Build a full-featured app with authentication and API integration',
    prerequisites: ['JavaScript basics'],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
  {
    id: 'skill-graphic-design',
    title: 'Graphic Design',
    summary: 'Create visual assets for brands, marketing, social media, and print using Canva, Photoshop, or Illustrator.',
    category: 'Design',
    tags: ['design', 'branding', 'canva', 'photoshop', 'visual'],
    iconName: 'Palette',
    difficulty: 'beginner',
    learningTimeWeeks: 6,
    monetizationPotential: ['Logo design', 'Social media graphics', 'Presentation design', 'Print design'],
    careerApplications: ['Graphic Designer', 'Brand Designer', 'Marketing Designer'],
    beginnerProject: 'Design a logo and brand kit for a fictional brand',
    portfolioProject: 'Create a complete brand identity system with guidelines',
    prerequisites: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
  {
    id: 'skill-podcasting',
    title: 'Podcasting',
    summary: 'Plan, record, edit, and distribute your own podcast or audio content.',
    category: 'Creative',
    tags: ['audio', 'podcast', 'content-creation', 'storytelling'],
    iconName: 'Video',
    difficulty: 'beginner',
    learningTimeWeeks: 4,
    monetizationPotential: ['Sponsorships', 'Brand collaborations', 'Premium content', 'Affiliate marketing'],
    careerApplications: ['Podcast Producer', 'Audio Content Creator', 'Media Host'],
    beginnerProject: 'Record and publish a 3-episode mini-series',
    portfolioProject: 'Launch a themed podcast with consistent branding and 10+ episodes',
    prerequisites: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
  {
    id: 'skill-public-speaking',
    title: 'Public Speaking',
    summary: 'Communicate ideas with confidence and clarity in presentations, pitches, and debates.',
    category: 'Business',
    tags: ['speaking', 'presentation', 'communication', 'leadership'],
    iconName: 'Megaphone',
    difficulty: 'beginner',
    learningTimeWeeks: 8,
    monetizationPotential: ['Workshop facilitation', 'Event hosting', 'Corporate training', 'Debate coaching'],
    careerApplications: ['Public Speaker', 'Trainer', 'Event Host', 'Sales Professional'],
    beginnerProject: 'Deliver a 5-minute talk on a topic you care about',
    portfolioProject: 'Host a campus workshop and record it for your portfolio',
    prerequisites: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
];

// ============================================================
// OPPORTUNITIES
// All demo data — not real listings
// ============================================================

export const demoOpportunities: Opportunity[] = [
  {
    id: 'opp-1',
    title: 'Software Engineering Intern',
    summary: 'Build and scale products at a high-growth YC startup.',
    category: 'Tech',
    tags: ['software', 'internship', 'remote'],
    type: 'internship',
    organization: 'Wellfound (AngelList)',
    location: 'Remote',
    deadline: 'Rolling Basis',
    eligibility: 'CS/IT students, strong in React/Node',
    link: 'https://wellfound.com/role/software-engineer-interns',
    compensation: '₹15,000–30,000/month',
    remote: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'verified',
  },
  {
    id: 'opp-2',
    title: 'Smart India Hackathon 2027',
    summary: 'Nationwide initiative to provide students a platform to solve some of the pressing problems we face.',
    category: 'Tech',
    tags: ['hackathon', 'competition'],
    type: 'hackathon',
    organization: 'Govt. of India',
    location: 'Multiple Cities',
    deadline: 'Jan 2027',
    eligibility: 'All college students',
    link: 'https://www.sih.gov.in/',
    remote: false,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'verified',
  },
  {
    id: 'opp-3',
    title: 'Freelance Content Writer',
    summary: 'Write high-quality technical blogs and articles for developer platforms.',
    category: 'Writing',
    tags: ['freelance', 'writing', 'remote'],
    type: 'freelance',
    organization: 'Internshala',
    location: 'Remote',
    eligibility: 'Excellent writing skills',
    link: 'https://internshala.com/internships/content-writing-internship/',
    compensation: '₹1,000–3,000/article',
    remote: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'verified',
  },
  {
    id: 'opp-4',
    title: 'Campus Ambassador Program',
    summary: 'Represent top brands on your campus, organize events, and earn stipends and certificates.',
    category: 'Marketing',
    tags: ['campus', 'marketing'],
    type: 'campus_job',
    organization: 'Unstop',
    location: 'Pan India',
    eligibility: 'Active college students',
    link: 'https://unstop.com/campus-ambassador-programs',
    compensation: 'Performance based',
    remote: false,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'verified',
  },
  {
    id: 'opp-5',
    title: 'Google Summer of Code (GSoC)',
    summary: 'Global program focused on bringing student developers into open source software development.',
    category: 'Tech',
    tags: ['open-source', 'coding', 'stipend'],
    type: 'internship',
    organization: 'Google',
    location: 'Remote',
    deadline: 'April 2027',
    eligibility: 'Students 18+ years old',
    link: 'https://summerofcode.withgoogle.com/',
    compensation: '$1,500–$3,000 stipend',
    remote: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'verified',
  },
  {
    id: 'opp-6',
    title: 'Reliance Foundation Scholarship',
    summary: 'Providing support to undergraduate students across India to continue their education.',
    category: 'Finance',
    tags: ['scholarship', 'financial-aid'],
    type: 'scholarship',
    organization: 'Reliance Foundation',
    location: 'Pan India',
    deadline: 'Dec 2026',
    eligibility: 'First year UG students',
    link: 'https://scholarships.reliancefoundation.org/',
    compensation: 'Up to ₹2,00,000',
    remote: false,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'verified',
  },
  {
    id: 'opp-7',
    title: 'Designathon - UI/UX Challenge',
    summary: 'A 48-hour design challenge to create user-centric solutions for modern problems.',
    category: 'Design',
    tags: ['design', 'competition', 'uiux'],
    type: 'competition',
    organization: 'Devfolio',
    location: 'Remote',
    deadline: 'Next Month',
    eligibility: 'Design enthusiasts',
    link: 'https://devfolio.co/hackathons',
    compensation: 'Cash prizes',
    remote: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'verified',
  },
  {
    id: 'opp-8',
    title: 'Video Editing Freelancer',
    summary: 'Edit YouTube Shorts and Instagram Reels for educational creators.',
    category: 'Creative',
    tags: ['video', 'editing', 'freelance'],
    type: 'freelance',
    organization: 'Upwork',
    location: 'Remote',
    eligibility: 'Premiere Pro / After Effects skills',
    link: 'https://www.upwork.com/freelance-jobs/video-editing/',
    compensation: 'Hourly / Per Project',
    remote: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'verified',
  },
  {
    id: 'opp-9',
    title: 'Student Startup Pitch Competition',
    summary: 'Pitch your startup idea to angel investors and win seed funding.',
    category: 'Business',
    tags: ['startup', 'pitch', 'funding'],
    type: 'event',
    organization: 'E-Cell IIT Bombay',
    location: 'Mumbai',
    deadline: 'Jan 2027',
    eligibility: 'Student founders',
    link: 'https://www.ecell.in/',
    compensation: 'Funding up to ₹50 Lakhs',
    remote: false,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'verified',
  },
  {
    id: 'opp-10',
    title: 'Data Science Virtual Internship',
    summary: 'Learn data analysis and machine learning practically through virtual tasks.',
    category: 'Data',
    tags: ['data', 'machine-learning', 'internship'],
    type: 'internship',
    organization: 'Forage',
    location: 'Remote',
    eligibility: 'Anyone can join',
    link: 'https://www.theforage.com/',
    remote: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'verified',
  },
  {
    id: 'opp-11',
    title: 'LinkedIn Creator Accelerator',
    summary: 'A program to help emerging creators build their audience and monetize.',
    category: 'Creator',
    tags: ['creator', 'social-media', 'content'],
    type: 'creator',
    organization: 'LinkedIn',
    location: 'Remote',
    eligibility: 'Active LinkedIn creators',
    link: 'https://www.linkedin.com/creators/',
    compensation: 'Grant funding & tools',
    remote: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'verified',
  },
  {
    id: 'opp-12',
    title: 'YC Co-Founder Matching',
    summary: 'Find a co-founder for your next big idea from Y Combinator’s network.',
    category: 'Business',
    tags: ['startup', 'networking', 'founder'],
    type: 'event',
    organization: 'Y Combinator',
    location: 'Remote',
    eligibility: 'Anyone looking to build a startup',
    link: 'https://www.ycombinator.com/cofounder-match',
    remote: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'verified',
  }
];

// ============================================================
// TOOLS
// ============================================================

export const demoTools: Tool[] = [
  {
    id: 'tool-budget',
    name: 'Student Budget Calculator',
    description: 'Plan your monthly budget and track where your money goes.',
    category: 'Money',
    iconName: 'Calculator',
    route: '/tools#budget-calculator',
    status: 'published',
    isPremium: false,
  },
  {
    id: 'tool-savings',
    name: 'Savings Goal Calculator',
    description: 'Set a savings target and figure out how much to save weekly or monthly.',
    category: 'Money',
    iconName: 'PiggyBank',
    route: '/tools#savings-calculator',
    status: 'published',
    isPremium: false,
  },
  {
    id: 'tool-freelance-pricing',
    name: 'Freelance Pricing Calculator',
    description: 'Calculate what to charge for freelance work based on your skills and market.',
    category: 'Money',
    iconName: 'IndianRupee',
    route: '/tools#freelance-pricing',
    status: 'published',
    isPremium: false,
  },
  {
    id: 'tool-income-goal',
    name: 'Income Goal Planner',
    description: 'Plan your income target and see realistic pathways to reach it.',
    category: 'Money',
    iconName: 'Target',
    route: '/tools#income-goal',
    status: 'published',
    isPremium: false,
  },
  {
    id: 'tool-resume-checklist',
    name: 'Resume Checklist',
    description: 'Check if your resume has everything it needs before applying.',
    category: 'Career',
    iconName: 'ClipboardCheck',
    route: '/tools#resume-checklist',
    status: 'published',
    isPremium: false,
  },
  {
    id: 'tool-skill-quiz',
    name: '"What Should I Learn?" Quiz',
    description: 'Answer a few questions and get personalized skill recommendations.',
    category: 'Skills',
    iconName: 'HelpCircle',
    route: '/tools#skill-quiz',
    status: 'published',
    isPremium: false,
  },
  {
    id: 'tool-earn-quiz',
    name: '"How Can I Earn?" Quiz',
    description: 'Discover realistic earning opportunities based on your skills and time.',
    category: 'Money',
    iconName: 'Lightbulb',
    route: '/tools#earn-quiz',
    status: 'published',
    isPremium: false,
  },
  {
    id: 'tool-internship-tracker',
    name: 'Internship Application Tracker',
    description: 'Track all your internship applications in one place.',
    category: 'Career',
    iconName: 'ListChecks',
    route: '/tools#internship-tracker',
    status: 'coming_soon',
    isPremium: false,
  },
  {
    id: 'tool-time-planner',
    name: 'Study & Time Planner',
    description: 'Organize your week between classes, study, skills, and earning.',
    category: 'Life',
    iconName: 'Clock',
    route: '/tools#time-planner',
    status: 'coming_soon',
    isPremium: false,
  },
];

// ============================================================
// CAREER PATHS
// ============================================================

export const demoCareerPaths: CareerPath[] = [
  {
    id: 'career-tech',
    title: 'Tech & Engineering',
    summary: 'Build software, apps, systems, and digital products.',
    category: 'Tech',
    tags: ['coding', 'engineering', 'software'],
    direction: 'Tech',
    skills: ['Programming', 'Data Structures', 'System Design', 'Problem Solving'],
    avgSalaryRange: '₹4–25 LPA',
    demandLevel: 'high',
    steps: ['Learn programming fundamentals', 'Build projects', 'Contribute to open source', 'Get internships', 'Prepare for interviews'],
    iconName: 'Code2',
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
  {
    id: 'career-design',
    title: 'Design & Creative',
    summary: 'Create visual experiences, products, and brand identities.',
    category: 'Design',
    tags: ['design', 'ui-ux', 'creative'],
    direction: 'Design',
    skills: ['UI/UX Design', 'Visual Design', 'Prototyping', 'User Research'],
    avgSalaryRange: '₹3–18 LPA',
    demandLevel: 'high',
    steps: ['Learn design fundamentals', 'Master design tools', 'Build a portfolio', 'Get feedback', 'Apply to design roles'],
    iconName: 'Palette',
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
  {
    id: 'career-business',
    title: 'Business & Management',
    summary: 'Lead teams, build strategies, and drive organizational growth.',
    category: 'Business',
    tags: ['management', 'strategy', 'leadership'],
    direction: 'Business',
    skills: ['Communication', 'Analytics', 'Strategy', 'Leadership'],
    avgSalaryRange: '₹4–20 LPA',
    demandLevel: 'high',
    steps: ['Develop communication skills', 'Learn analytics', 'Get management exposure', 'Build case studies', 'Apply for business roles'],
    iconName: 'Briefcase',
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
  {
    id: 'career-finance',
    title: 'Finance & Consulting',
    summary: 'Analyze markets, manage money, and advise businesses.',
    category: 'Finance',
    tags: ['finance', 'consulting', 'analytics'],
    direction: 'Finance',
    skills: ['Financial Analysis', 'Excel', 'Presentation', 'Research'],
    avgSalaryRange: '₹5–25 LPA',
    demandLevel: 'high',
    steps: ['Learn financial fundamentals', 'Get certified (CFA/CA)', 'Build analytical skills', 'Get internships', 'Network actively'],
    iconName: 'TrendingUp',
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
  {
    id: 'career-media',
    title: 'Media & Content',
    summary: 'Create content, tell stories, and build media brands.',
    category: 'Media',
    tags: ['content', 'media', 'writing', 'video'],
    direction: 'Media',
    skills: ['Writing', 'Video Production', 'Social Media', 'Storytelling'],
    avgSalaryRange: '₹3–15 LPA',
    demandLevel: 'growing',
    steps: ['Choose a medium', 'Create consistently', 'Build an audience', 'Monetize content', 'Scale your brand'],
    iconName: 'Film',
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
  {
    id: 'career-research',
    title: 'Research & Academia',
    summary: 'Explore ideas, generate knowledge, and contribute to fields of study.',
    category: 'Research',
    tags: ['research', 'academia', 'science'],
    direction: 'Research',
    skills: ['Research Methods', 'Data Analysis', 'Academic Writing', 'Critical Thinking'],
    avgSalaryRange: '₹3–12 LPA',
    demandLevel: 'medium',
    steps: ['Pick a research area', 'Join a lab or project', 'Publish papers', 'Attend conferences', 'Apply for fellowships'],
    iconName: 'Microscope',
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
  {
    id: 'career-entrepreneurship',
    title: 'Entrepreneurship',
    summary: 'Start your own venture, build products, and create value.',
    category: 'Business',
    tags: ['startup', 'entrepreneurship', 'business'],
    direction: 'Entrepreneurship',
    skills: ['Problem Solving', 'Sales', 'Product Building', 'Financial Planning'],
    avgSalaryRange: 'Variable',
    demandLevel: 'growing',
    steps: ['Find a real problem', 'Validate the idea', 'Build an MVP', 'Get customers', 'Scale the business'],
    iconName: 'Rocket',
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
  {
    id: 'career-government',
    title: 'Government & Public Sector',
    summary: 'Serve in public administration, policy, or government services.',
    category: 'Government',
    tags: ['government', 'civil-services', 'public'],
    direction: 'Government',
    skills: ['General Knowledge', 'Communication', 'Analytical Writing', 'Ethics'],
    avgSalaryRange: '₹4–15 LPA',
    demandLevel: 'medium',
    steps: ['Understand exam patterns', 'Start preparation early', 'Join study groups', 'Take mock tests', 'Apply consistently'],
    iconName: 'Building2',
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
];

// ============================================================
// CAMPUS EVENTS
// ============================================================

export const demoCampusEvents: CampusEvent[] = [
  {
    id: 'campus-1',
    title: 'Inter-College Debate Championship',
    summary: 'Compete with students from colleges across the region in a structured debate format.',
    category: 'Competition',
    tags: ['debate', 'competition', 'public-speaking'],
    eventType: 'competition',
    city: 'Mumbai',
    eligibility: 'All undergraduate students',
    link: '#',
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
  {
    id: 'campus-2',
    title: 'Design Thinking Workshop',
    summary: 'A hands-on workshop on applying design thinking to real-world problems.',
    category: 'Workshop',
    tags: ['design', 'workshop', 'skills'],
    eventType: 'workshop',
    city: 'Bangalore',
    eligibility: 'Open to all',
    link: '#',
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
  {
    id: 'campus-3',
    title: 'Student Entrepreneurs Club',
    summary: 'A community of student founders sharing ideas, resources, and support.',
    category: 'Club',
    tags: ['entrepreneurship', 'club', 'community'],
    eventType: 'club',
    eligibility: 'Any student interested in entrepreneurship',
    link: '#',
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
  {
    id: 'campus-4',
    title: 'National Student Discount Card',
    summary: 'Get verified student discounts at restaurants, software, travel, and more.',
    category: 'Discount',
    tags: ['discount', 'savings', 'student-life'],
    eventType: 'discount',
    eligibility: 'Valid student ID required',
    link: '#',
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
  {
    id: 'campus-5',
    title: 'Coding Bootcamp Weekend',
    summary: 'Intensive 2-day coding bootcamp covering web development fundamentals and deployment.',
    category: 'Workshop',
    tags: ['coding', 'bootcamp', 'web-dev'],
    eventType: 'workshop',
    city: 'Hyderabad',
    eligibility: 'Beginners welcome',
    link: '#',
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
  {
    id: 'campus-6',
    title: 'National Scholarship Fair 2027',
    summary: 'Meet representatives from scholarship organizations and learn about funding opportunities.',
    category: 'Scholarship',
    tags: ['scholarship', 'financial-aid', 'education'],
    eventType: 'scholarship',
    city: 'Delhi',
    eligibility: 'All students',
    link: '#',
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
  {
    id: 'campus-7',
    title: 'Build-a-Thon: Social Impact',
    summary: 'Build tech solutions for social good. 48-hour hackathon with NGO partnerships.',
    category: 'Hackathon',
    tags: ['hackathon', 'social-impact', 'tech'],
    eventType: 'hackathon',
    city: 'Pune',
    eligibility: 'Teams of 2–5, any discipline',
    link: '#',
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
  {
    id: 'campus-8',
    title: 'Photography & Visual Arts Club',
    summary: 'Join a community of student photographers. Monthly meetups, critiques, and exhibitions.',
    category: 'Club',
    tags: ['photography', 'art', 'community'],
    eventType: 'club',
    city: 'Delhi',
    eligibility: 'All levels welcome',
    link: '#',
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    status: 'published',
    verificationStatus: 'demo',
  },
];

// ============================================================
// PILLAR DATA
// ============================================================

export const pillars = [
  {
    id: 'money',
    title: 'Money',
    tagline: 'Earn smart. Spend wise.',
    description: 'Discover legitimate ways to earn, manage your budget, and build financial independence as a student.',
    href: '/money',
    iconName: 'IndianRupee',
    color: '#B7F34A',
    features: ['Earning pathways', 'Budget tools', 'Freelance pricing', 'Financial literacy'],
  },
  {
    id: 'skills',
    title: 'Skills',
    tagline: 'Learn. Build. Prove.',
    description: 'Develop practical, market-ready skills through projects, roadmaps, and portfolio building.',
    href: '/skills',
    iconName: 'Zap',
    color: '#3157D5',
    features: ['Skill roadmaps', 'Project-based learning', 'Portfolio building', 'Certification guides'],
  },
  {
    id: 'career',
    title: 'Career',
    tagline: 'Build before you apply.',
    description: 'Turn your skills and experience into career opportunities through internships, jobs, and networking.',
    href: '/career',
    iconName: 'Briefcase',
    color: '#111111',
    features: ['Career paths', 'Resume building', 'Interview prep', 'Networking guides'],
  },
  {
    id: 'campus',
    title: 'Campus',
    tagline: 'Get more from college.',
    description: 'Find events, clubs, competitions, scholarships, and opportunities on and around your campus.',
    href: '/campus',
    iconName: 'GraduationCap',
    color: '#3157D5',
    features: ['Events & hackathons', 'Clubs & communities', 'Scholarships', 'Student discounts'],
  },
  {
    id: 'life',
    title: 'Life',
    tagline: 'Become capable. Not just qualified.',
    description: 'Build independence with practical skills in productivity, communication, networking, and adulting.',
    href: '/life',
    iconName: 'Compass',
    color: '#B7F34A',
    features: ['Productivity systems', 'Communication skills', 'Personal branding', 'Decision making'],
  },
];

// ============================================================
// STUDENT JOURNEY
// ============================================================

export const studentJourney = [
  {
    stage: 'START',
    question: "I'm in college. What should I actually do?",
    description: 'Understand the gap between college and real life. Start thinking beyond your degree.',
    color: '#8E8E8E',
  },
  {
    stage: 'LEARN',
    question: 'What skills should I develop?',
    description: 'Discover practical, marketable skills that match your interests and career goals.',
    color: '#3157D5',
  },
  {
    stage: 'BUILD',
    question: 'What can I show people that I can do?',
    description: 'Create projects, portfolios, and proof of your abilities.',
    color: '#3157D5',
  },
  {
    stage: 'EARN',
    question: 'How can I turn those skills into income?',
    description: 'Find freelancing, part-time, and skill-based earning opportunities.',
    color: '#B7F34A',
  },
  {
    stage: 'LAUNCH',
    question: 'How do I turn this into a career?',
    description: 'Get internships, jobs, or start your own venture with what you\'ve built.',
    color: '#111111',
  },
  {
    stage: 'INDEPENDENCE',
    question: 'How do I manage my money, career, and life?',
    description: 'Become a capable adult who can navigate the real world confidently.',
    color: '#111111',
  },
];

// ============================================================
// EARNING PATHWAYS
// ============================================================

export const earningPathways = [
  {
    title: 'Freelancing',
    description: 'Offer your skills as services to clients worldwide.',
    examples: ['Web design', 'Content writing', 'Video editing', 'Social media management'],
    difficulty: 'Medium',
    timeToFirstEarning: '2–4 weeks',
    iconName: 'Laptop',
  },
  {
    title: 'Part-time Work',
    description: 'Find flexible work that fits around your college schedule.',
    examples: ['Tutoring', 'Retail', 'Campus jobs', 'Event staffing'],
    difficulty: 'Easy',
    timeToFirstEarning: '1–2 weeks',
    iconName: 'Clock',
  },
  {
    title: 'Internships',
    description: 'Get paid while learning from experienced professionals.',
    examples: ['Tech internships', 'Marketing internships', 'Design internships', 'Research assistantships'],
    difficulty: 'Medium',
    timeToFirstEarning: '4–8 weeks',
    iconName: 'Building2',
  },
  {
    title: 'Creator Economy',
    description: 'Create content and build an audience on platforms.',
    examples: ['YouTube', 'Instagram', 'Blogging', 'Newsletters'],
    difficulty: 'Hard',
    timeToFirstEarning: '2–6 months',
    iconName: 'Sparkles',
  },
  {
    title: 'Campus Opportunities',
    description: 'Earn through activities and roles within your college.',
    examples: ['Teaching assistant', 'Event organizing', 'Campus ambassador', 'Research projects'],
    difficulty: 'Easy',
    timeToFirstEarning: '1–3 weeks',
    iconName: 'GraduationCap',
  },
  {
    title: 'Skill-based Services',
    description: 'Turn specific skills into local or online services.',
    examples: ['Photography', 'Presentation design', 'Research assistance', 'Data visualization'],
    difficulty: 'Easy',
    timeToFirstEarning: '1–2 weeks',
    iconName: 'Wrench',
  },
];

// ============================================================
// LIFE CATEGORIES
// ============================================================

export const lifeCategories = [
  {
    title: 'Productivity',
    description: 'Manage your time, energy, and tasks like someone who actually gets things done.',
    actionable: 'Build a weekly system that balances classes, skills, and earning.',
    iconName: 'Zap',
    topics: ['Time blocking', 'Task management', 'Focus techniques', 'Energy management'],
  },
  {
    title: 'Communication',
    description: 'Speak, write, and present with clarity and confidence.',
    actionable: 'Practice one communication skill this week — email, pitch, or presentation.',
    iconName: 'MessageSquare',
    topics: ['Email etiquette', 'Public speaking', 'Active listening', 'Writing clearly'],
  },
  {
    title: 'Networking',
    description: 'Build real relationships that open doors, not just collect contacts.',
    actionable: 'Reach out to one person in your field this week with a genuine message.',
    iconName: 'Users',
    topics: ['LinkedIn strategy', 'Cold outreach', 'Informational interviews', 'Building relationships'],
  },
  {
    title: 'Confidence & Mindset',
    description: 'Develop the resilience and self-belief to pursue what matters.',
    actionable: 'Identify one fear holding you back and take a small step toward it.',
    iconName: 'Shield',
    topics: ['Imposter syndrome', 'Growth mindset', 'Handling rejection', 'Self-advocacy'],
  },
  {
    title: 'Organization',
    description: 'Keep your academic, professional, and personal life in order.',
    actionable: 'Set up a simple digital system for notes, files, and deadlines.',
    iconName: 'FolderOpen',
    topics: ['Digital organization', 'Note-taking systems', 'File management', 'Calendar strategy'],
  },
  {
    title: 'Adulting',
    description: 'Navigate the things nobody taught you in school — from taxes to cooking.',
    actionable: 'Learn one new practical skill this month — cooking, budgeting, or filing.',
    iconName: 'Home',
    topics: ['Basic cooking', 'Laundry & cleaning', 'Tax basics', 'Renting & housing'],
  },
  {
    title: 'Decision Making',
    description: 'Make better choices about your career, money, and life.',
    actionable: 'Write down the pros/cons of one decision you\'re currently postponing.',
    iconName: 'GitBranch',
    topics: ['Framework thinking', 'Risk assessment', 'Opportunity cost', 'Long-term thinking'],
  },
  {
    title: 'Personal Branding',
    description: 'Build a reputation that works for you — online and offline.',
    actionable: 'Update your LinkedIn headline to reflect what you actually do.',
    iconName: 'UserCheck',
    topics: ['LinkedIn profile', 'Portfolio building', 'Online presence', 'Professional identity'],
  },
];
